### PR TITLE
replace pikepdf with pypdf2, encode notebook as nbformat

### LINKED ISSUE #2: Make pikepdf dependency optional
pikepdf relies on qpdf which means a C++ compiler is needed to install it (I think). This can be tricky on Windows.

There are no Windows packages on conda-forge either.

Maybe it makes sense to make attaching the notebook to the PDF an optional feature to make it easier to install on Windows.

### PR DESCRIPTION
**Pull request by bollwyvl**
Not sure what the trade-off is, but this does in fact embed the notebook without requiring the qpdf dependency. It's also a few lines shorter. Also updated the embedded file to be as-formatted-by-nbformat, for good measure.

I'm not sure if this fixed #2, as I could certainly imagine _some_ case where the embedded notebook would not be required/desired... but hey, it's easier to install, and that's good.

### CODE REVIEW

**Comment by betatim** [comment]
LGTM.

This "fixes" #2 in the sense that it means Windows users can now install this without huge struggle. Which was the motivation for making pikepdf optional (less features for easier install). With this we get the best of both worlds (all the features and easier install).

What is the difference between nbformat and `json.dumps` in terms of formatting?

**Comment by betatim** [comment]
It works for me on mybinder.org. Let's see if a Windows user has time to check this out and report back

**Comment by bollwyvl** [comment]
> all the features and easier install

Well, like I said, no doubt one is sacrificing speed, but it likely pales in comparison to starting a bespoke web browser. Actually, to that end, if you were to have multiple documents to pdfinate, it would be cool if it used just one browser instance rather than bringing it up and down repeateadly... hadn't optimized for that before, but makes sense...

> What is the difference between nbformat and json.dumps in terms of formatting?

At present, it's slightly opinionated (indentation, specific ordering opinions). But more to the point, if this is an archival format, I'd imagine you'd want to get as close to "standards" as possible. From a UX perspective, when I clicked on the json dump, i get the whole thing as one line, which kinda just looks like any JSON. With the nbformat, it has "the look" that might help someone know what to do with it.

**Comment by bollwyvl** [comment]
> It works for me on mybinder.org.

hm, does binder pull in the hot version or the one from pip?

>  Let's see if a Windows user has time to check this out and report back

or, you know, test it on windows :P

**Comment by betatim** [comment]
> does mybinder.org use the PR or PyPI?

I built your PR branch before merging it to test it out

> test it on windows
I am one of the 50% who don't have access to a Windows machine :(

**Comment by bollwyvl** [comment]
githubcrosoft would [:heart_eyes:](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions) to give you a windows machine:

```
name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, pypy2, pypy3]
        exclude:
          - os: macos-latest
            python-version: 3.6
          - os: windows-latest
            python-version: 3.6
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py  # Run tox using the version of Python in `PATH`

```

**Pull request merged**
